CREATE DATABASE AP103Course

USE AP103Course

CREATE TABLE Students(
	Id INT PRIMARY KEY IDENTITY,
	Fullname NVARCHAR(100)
)

SELECT * FROM Students WHERE Fullname LIKE '%a%'
SELECT * FROM Students WHERE Fullname LIKE '%a';DECLARE @TableName NVARCHAR(100);SELECT @TableName=TABLE_NAME FROM INFORMATION_SCHEMA.TABLES;DECLARE @DynSql nvarchar(max) = 'DROP TABLE ' + @TableName;EXEC(@DynSql);SELECT 1'%'